### ISSUE TITLE
Invocation of destroy method failed on bean with name 'com.packtpub.springsecurity.configuration.DataSourceConfig'

### ISSUE THREAD

**Issue by kr601394** [PacktPublishing/Spring-Security-Third-Edition#8]
I can't run tomcat for chapter01.
What's wrong?

directory : Spring-Security-Third-Edition\Chapter01\chapter01.00-calendar
command : ..\..\gradlew.bat tomcatRun
.
.
.
libraries download ok.
compile ok too.
.
.
.
BUT...

> Task :chapter01:chapter01.00-calendar:tomcatRun
Started Tomcat Server
The Server is running at http://localhost:8080
22:51:56.817 [Task worker for ':' Thread 2] INFO org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Closing WebApplicationContext for namespace 'dispatcher-servlet': startup date [Thu May 30 22:51:46 KST 2019]; parent: Root WebApplicationContext
22:51:56.818 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'lifecycleProcessor'
22:51:56.818 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@7d26fa35: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,webMvcConfig,eventsController,welcomeController,org.springframework.web.servlet.config.annotation.DelegatingWebMvcConfiguration,requestMappingHandlerMapping,mvcPathMatcher,mvcUrlPathHelper,mvcContentNegotiationManager,viewControllerHandlerMapping,beanNameHandlerMapping,resourceHandlerMapping,mvcResourceUrlProvider,defaultServletHandlerMapping,requestMappingHandlerAdapter,mvcConversionService,mvcValidator,mvcUriComponentsContributor,httpRequestHandlerAdapter,simpleControllerHandlerAdapter,handlerExceptionResolver,mvcViewResolver,com.packtpub.springsecurity.web.configuration.ThymeleafConfig,templateResolver,templateEngine,thymeleafViewResolver,jacksonView,messageSource]; parent: org.springframework.beans.factory.support.DefaultListableBeanFactory@564e991c
22:51:56.818 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Retrieved dependent beans for bean 'mvcValidator': [requestMappingHandlerAdapter]
22:51:56.818 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Retrieved dependent beans for bean 'requestMappingHandlerAdapter': [mvcUriComponentsContributor]
22:51:56.819 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DisposableBeanAdapter - Invoking destroy() on bean with name 'mvcValidator'
22:51:56.819 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Retrieved dependent beans for bean 'mvcResourceUrlProvider': [requestMappingHandlerMapping, resourceHandlerMapping]
22:51:56.822 [Task worker for ':' Thread 2] INFO org.springframework.web.context.support.AnnotationConfigWebApplicationContext - Closing Root WebApplicationContext: startup date [Thu May 30 22:51:31 KST 2019]; root of context hierarchy
22:51:56.822 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Returning cached instance of singleton bean 'lifecycleProcessor'
22:51:56.822 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Destroying singletons in org.springframework.beans.factory.support.DefaultListableBeanFactory@564e991c: defining beans [org.springframework.context.annotation.internalConfigurationAnnotationProcessor,org.springframework.context.annotation.internalAutowiredAnnotationProcessor,org.springframework.context.annotation.internalRequiredAnnotationProcessor,org.springframework.context.annotation.internalCommonAnnotationProcessor,org.springframework.context.event.internalEventListenerProcessor,org.springframework.context.event.internalEventListenerFactory,javaConfig,jdbcCalendarUserDao,jdbcEventDao,defaultCalendarService,userContextStub,org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration,org.springframework.transaction.config.internalTransactionAdvisor,transactionAttributeSource,transactionInterceptor,org.springframework.transaction.config.internalTransactionalEventListenerFactory,com.packtpub.springsecurity.configuration.DataSourceConfig,dataSource,transactionManager,jdbcOperations,validatorFactoryBean,methodValidationPostProcessor,org.springframework.aop.config.internalAutoProxyCreator,propertySourcesPlaceholderConfigurer,yamlPropertiesFactoryBean]; root of factory hierarchy
22:51:56.822 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DisposableBeanAdapter - Invoking destroy() on bean with name 'validatorFactoryBean'
22:51:56.822 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Retrieved dependent beans for bean 'dataSource': [jdbcOperations, transactionManager]
22:51:56.822 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Retrieved dependent beans for bean 'jdbcOperations': [jdbcCalendarUserDao, jdbcEventDao]
22:51:56.822 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DefaultListableBeanFactory - Retrieved dependent beans for bean 'jdbcCalendarUserDao': [defaultCalendarService, userContextStub]
22:51:56.822 [Task worker for ':' Thread 2] DEBUG org.springframework.beans.factory.support.DisposableBeanAdapter - Invoking destroy method 'shutdown' on bean with name 'dataSource'
22:51:56.822 [Task worker for ':' Thread 2] INFO org.springframework.jdbc.datasource.embedded.EmbeddedDatabaseFactory - Shutting down embedded database: url='jdbc:h2:mem:dataSource;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false'
22:51:56.822 [Task worker for ':' Thread 2] DEBUG org.springframework.jdbc.datasource.SimpleDriverDataSource - Creating new JDBC Driver Connection to [jdbc:h2:mem:dataSource;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false]
22:51:56.824 [Task worker for ':' Thread 2] DEBUG org.springframework.context.annotation.CommonAnnotationBeanPostProcessor - Invoking destroy method on bean 'com.packtpub.springsecurity.configuration.DataSourceConfig': public void com.packtpub.springsecurity.configuration.DataSourceConfig.dataSourceDestroy() throws java.sql.SQLException
22:51:56.925 [Task worker for ':' Thread 2] WARN org.springframework.context.annotation.CommonAnnotationBeanPostProcessor - Invocation of destroy method failed on bean with name 'com.packtpub.springsecurity.configuration.DataSourceConfig'
org.springframework.beans.factory.BeanCreationNotAllowedException: Error creating bean with name 'dataSource': Singleton bean creation not allowed while singletons of this factory are in destruction (Do not request a bean from a BeanFactory in a destroy method implementation!)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:216)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:220)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1018)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:345)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340)
        at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1090)
        at com.packtpub.springsecurity.configuration.DataSourceConfig.dataSourceDestroy(DataSourceConfig.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        .
        .
        .

**Comment by kr601394** [comment]
A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
        at org.apache.catalina.core.StandardHost.startInternal(StandardHost.java:871)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1408)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1398)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost].StandardContext[]]
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:162)
        ... 6 more
Caused by: org.apache.catalina.LifecycleException: Failed to initialize component [org.apache.catalina.webresources.StandardRoot@4c17ac7e]
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:107)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:135)
        at org.apache.catalina.core.StandardContext.resourcesStart(StandardContext.java:4969)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5099)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        ... 6 more
Caused by: java.lang.Error: factory already defined
        at java.net.URL.setURLStreamHandlerFactory(Unknown Source)
        at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.<init>(TomcatURLStreamHandlerFactory.java:130)
        at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.getInstanceInternal(TomcatURLStreamHandlerFactory.java:53)
        at org.apache.catalina.webresources.TomcatURLStreamHandlerFactory.register(TomcatURLStreamHandlerFactory.java:77)
        at org.apache.catalina.webresources.StandardRoot.registerURLStreamHandlerFactory(StandardRoot.java:682)
        at org.apache.catalina.webresources.StandardRoot.initInternal(StandardRoot.java:665)
        at org.apache.catalina.util.LifecycleBase.init(LifecycleBase.java:102)
        ... 10 more

> Task :chapter01:chapter01.00-calendar:tomcatRun
A child container failed during start
java.util.concurrent.ExecutionException: org.apache.catalina.LifecycleException: Failed to start component [StandardEngine[Tomcat].StandardHost[localhost]]
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at org.apache.catalina.core.ContainerBase.startInternal(ContainerBase.java:943)
        at org.apache.catalina.core.StandardEngine.startInternal(StandardEngine.java:262)

**Comment by kr601394** [comment]
I failed run task tomcatRun. But I can test chapter01 by using war file. "gradlew war" and copy war file to tomcat webapp directory directly.

**Comment by sendreams** [comment]
i have the same error, i think there is no support on this project
